### ISSUE TITLE
Deprecated ....

### ISSUE THREAD

**Issue by astromik** [Ovsyanka/email_saver#6]
Hello.
My PHP version is 7.
Warning message appears in the class module:

"Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; receiveMail has a deprecated constructor....".

I think here is a solution, but my knowledge is not enough :
  https://cweiske.de/tagebuch/php4-constructors-php7.htm

**Comment by Ovsyanka** [comment]
Actually I surprized that someone noticed and using it =) That script was written for php 5 initially, but in case you using it I suppose to fix this in few days.

**Comment by Ovsyanka** [comment]
I fixed this in the `issue/6` branch. Can you test it please? I dont have testing environment right now.

**Comment by astromik** [comment]
For my presonal needs I had to change line 40 in the file 'receivemail.class.php'
from the original:
  ` $strConnect='{'.$mailserver.':'.$port. '/pop3'.($ssl ? "/ssl" : "").'}INBOX'; `
to this:
  `$strConnect="{mx.endora.cz:110/pop3/notls/novalidate-cert}INBOX";`

Now everything works great.

Thank you very much.

**Comment by Ovsyanka** [comment]
Okay, I pushed changes to the master branch.

About your `$strConnect` changes. Actually it is not related to current issue. It will be nice if you will post another issue with that information (you can just copy-paste). It is not good to modify source code for things like that and i should add the possibility to change connect string throught settings.

**Comment by Ovsyanka** [comment]
Hm, actually now i see, that there is no using of receiveMail class at all. I am not sure why I didn't delete it.
